// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *API) DeepCopyInto(out *API) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new API.
func (in *API) DeepCopy() *API {
	if in == nil {
		return nil
	}
	out := new(API)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *API) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIBase) DeepCopyInto(out *APIBase) {
	*out = *in
	in.IntegrationMethod.DeepCopyInto(&out.IntegrationMethod)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIBase.
func (in *APIBase) DeepCopy() *APIBase {
	if in == nil {
		return nil
	}
	out := new(APIBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIBaseInternal) DeepCopyInto(out *APIBaseInternal) {
	*out = *in
	in.APIBase.DeepCopyInto(&out.APIBase)
	in.IntegrationMethod.DeepCopyInto(&out.IntegrationMethod)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIBaseInternal.
func (in *APIBaseInternal) DeepCopy() *APIBaseInternal {
	if in == nil {
		return nil
	}
	out := new(APIBaseInternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIKey) DeepCopyInto(out *APIKey) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIKey.
func (in *APIKey) DeepCopy() *APIKey {
	if in == nil {
		return nil
	}
	out := new(APIKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIList) DeepCopyInto(out *APIList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]API, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIList.
func (in *APIList) DeepCopy() *APIList {
	if in == nil {
		return nil
	}
	out := new(APIList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIPair) DeepCopyInto(out *APIPair) {
	*out = *in
	in.A.DeepCopyInto(&out.A)
	in.B.DeepCopyInto(&out.B)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIPair.
func (in *APIPair) DeepCopy() *APIPair {
	if in == nil {
		return nil
	}
	out := new(APIPair)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APISelectors) DeepCopyInto(out *APISelectors) {
	*out = *in
	in.PlanSelector.DeepCopyInto(&out.PlanSelector)
	in.MetricSelector.DeepCopyInto(&out.MetricSelector)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APISelectors.
func (in *APISelectors) DeepCopy() *APISelectors {
	if in == nil {
		return nil
	}
	out := new(APISelectors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APISpec) DeepCopyInto(out *APISpec) {
	*out = *in
	in.APIBase.DeepCopyInto(&out.APIBase)
	in.APISelectors.DeepCopyInto(&out.APISelectors)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APISpec.
func (in *APISpec) DeepCopy() *APISpec {
	if in == nil {
		return nil
	}
	out := new(APISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIStatus) DeepCopyInto(out *APIStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIStatus.
func (in *APIStatus) DeepCopy() *APIStatus {
	if in == nil {
		return nil
	}
	out := new(APIStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIcastBaseOptions) DeepCopyInto(out *APIcastBaseOptions) {
	*out = *in
	in.AuthenticationSettings.DeepCopyInto(&out.AuthenticationSettings)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIcastBaseOptions.
func (in *APIcastBaseOptions) DeepCopy() *APIcastBaseOptions {
	if in == nil {
		return nil
	}
	out := new(APIcastBaseOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIcastBaseSelectors) DeepCopyInto(out *APIcastBaseSelectors) {
	*out = *in
	in.MappingRulesSelector.DeepCopyInto(&out.MappingRulesSelector)
	in.PoliciesSelector.DeepCopyInto(&out.PoliciesSelector)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIcastBaseSelectors.
func (in *APIcastBaseSelectors) DeepCopy() *APIcastBaseSelectors {
	if in == nil {
		return nil
	}
	out := new(APIcastBaseSelectors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIsDiff) DeepCopyInto(out *APIsDiff) {
	*out = *in
	if in.MissingFromA != nil {
		in, out := &in.MissingFromA, &out.MissingFromA
		*out = make([]InternalAPI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MissingFromB != nil {
		in, out := &in.MissingFromB, &out.MissingFromB
		*out = make([]InternalAPI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Equal != nil {
		in, out := &in.Equal, &out.Equal
		*out = make([]InternalAPI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NotEqual != nil {
		in, out := &in.NotEqual, &out.NotEqual
		*out = make([]APIPair, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIsDiff.
func (in *APIsDiff) DeepCopy() *APIsDiff {
	if in == nil {
		return nil
	}
	out := new(APIsDiff)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApicastAuthenticationSettings) DeepCopyInto(out *ApicastAuthenticationSettings) {
	*out = *in
	in.Credentials.DeepCopyInto(&out.Credentials)
	out.Errors = in.Errors
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApicastAuthenticationSettings.
func (in *ApicastAuthenticationSettings) DeepCopy() *ApicastAuthenticationSettings {
	if in == nil {
		return nil
	}
	out := new(ApicastAuthenticationSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApicastHosted) DeepCopyInto(out *ApicastHosted) {
	*out = *in
	in.APIcastBaseOptions.DeepCopyInto(&out.APIcastBaseOptions)
	in.APIcastBaseSelectors.DeepCopyInto(&out.APIcastBaseSelectors)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApicastHosted.
func (in *ApicastHosted) DeepCopy() *ApicastHosted {
	if in == nil {
		return nil
	}
	out := new(ApicastHosted)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApicastOnPrem) DeepCopyInto(out *ApicastOnPrem) {
	*out = *in
	in.APIcastBaseOptions.DeepCopyInto(&out.APIcastBaseOptions)
	in.APIcastBaseSelectors.DeepCopyInto(&out.APIcastBaseSelectors)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApicastOnPrem.
func (in *ApicastOnPrem) DeepCopy() *ApicastOnPrem {
	if in == nil {
		return nil
	}
	out := new(ApicastOnPrem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppID) DeepCopyInto(out *AppID) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppID.
func (in *AppID) DeepCopy() *AppID {
	if in == nil {
		return nil
	}
	out := new(AppID)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Authentication) DeepCopyInto(out *Authentication) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Authentication.
func (in *Authentication) DeepCopy() *Authentication {
	if in == nil {
		return nil
	}
	out := new(Authentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Binding) DeepCopyInto(out *Binding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Binding.
func (in *Binding) DeepCopy() *Binding {
	if in == nil {
		return nil
	}
	out := new(Binding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Binding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindingList) DeepCopyInto(out *BindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Binding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindingList.
func (in *BindingList) DeepCopy() *BindingList {
	if in == nil {
		return nil
	}
	out := new(BindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindingSpec) DeepCopyInto(out *BindingSpec) {
	*out = *in
	out.CredentialsRef = in.CredentialsRef
	in.APISelector.DeepCopyInto(&out.APISelector)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindingSpec.
func (in *BindingSpec) DeepCopy() *BindingSpec {
	if in == nil {
		return nil
	}
	out := new(BindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindingStatus) DeepCopyInto(out *BindingStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindingStatus.
func (in *BindingStatus) DeepCopy() *BindingStatus {
	if in == nil {
		return nil
	}
	out := new(BindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodePlugin) DeepCopyInto(out *CodePlugin) {
	*out = *in
	in.AuthenticationSettings.DeepCopyInto(&out.AuthenticationSettings)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodePlugin.
func (in *CodePlugin) DeepCopy() *CodePlugin {
	if in == nil {
		return nil
	}
	out := new(CodePlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodePluginAuthenticationSettings) DeepCopyInto(out *CodePluginAuthenticationSettings) {
	*out = *in
	in.Credentials.DeepCopyInto(&out.Credentials)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodePluginAuthenticationSettings.
func (in *CodePluginAuthenticationSettings) DeepCopy() *CodePluginAuthenticationSettings {
	if in == nil {
		return nil
	}
	out := new(CodePluginAuthenticationSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Consolidated) DeepCopyInto(out *Consolidated) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Consolidated.
func (in *Consolidated) DeepCopy() *Consolidated {
	if in == nil {
		return nil
	}
	out := new(Consolidated)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Consolidated) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsolidatedList) DeepCopyInto(out *ConsolidatedList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Consolidated, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsolidatedList.
func (in *ConsolidatedList) DeepCopy() *ConsolidatedList {
	if in == nil {
		return nil
	}
	out := new(ConsolidatedList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConsolidatedList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsolidatedSpec) DeepCopyInto(out *ConsolidatedSpec) {
	*out = *in
	out.Credentials = in.Credentials
	if in.APIs != nil {
		in, out := &in.APIs, &out.APIs
		*out = make([]InternalAPI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsolidatedSpec.
func (in *ConsolidatedSpec) DeepCopy() *ConsolidatedSpec {
	if in == nil {
		return nil
	}
	out := new(ConsolidatedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsolidatedStatus) DeepCopyInto(out *ConsolidatedStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsolidatedStatus.
func (in *ConsolidatedStatus) DeepCopy() *ConsolidatedStatus {
	if in == nil {
		return nil
	}
	out := new(ConsolidatedStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Errors) DeepCopyInto(out *Errors) {
	*out = *in
	out.AuthenticationFailed = in.AuthenticationFailed
	out.AuthenticationMissing = in.AuthenticationMissing
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Errors.
func (in *Errors) DeepCopy() *Errors {
	if in == nil {
		return nil
	}
	out := new(Errors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationCredentials) DeepCopyInto(out *IntegrationCredentials) {
	*out = *in
	if in.APIKey != nil {
		in, out := &in.APIKey, &out.APIKey
		*out = new(APIKey)
		**out = **in
	}
	if in.AppID != nil {
		in, out := &in.AppID, &out.AppID
		*out = new(AppID)
		**out = **in
	}
	if in.OpenIDConnector != nil {
		in, out := &in.OpenIDConnector, &out.OpenIDConnector
		*out = new(OpenIDConnector)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationCredentials.
func (in *IntegrationCredentials) DeepCopy() *IntegrationCredentials {
	if in == nil {
		return nil
	}
	out := new(IntegrationCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationMethod) DeepCopyInto(out *IntegrationMethod) {
	*out = *in
	if in.ApicastOnPrem != nil {
		in, out := &in.ApicastOnPrem, &out.ApicastOnPrem
		*out = new(ApicastOnPrem)
		(*in).DeepCopyInto(*out)
	}
	if in.CodePlugin != nil {
		in, out := &in.CodePlugin, &out.CodePlugin
		*out = new(CodePlugin)
		(*in).DeepCopyInto(*out)
	}
	if in.ApicastHosted != nil {
		in, out := &in.ApicastHosted, &out.ApicastHosted
		*out = new(ApicastHosted)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationMethod.
func (in *IntegrationMethod) DeepCopy() *IntegrationMethod {
	if in == nil {
		return nil
	}
	out := new(IntegrationMethod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalAPI) DeepCopyInto(out *InternalAPI) {
	*out = *in
	in.APIBaseInternal.DeepCopyInto(&out.APIBaseInternal)
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]InternalMetric, len(*in))
		copy(*out, *in)
	}
	if in.Plans != nil {
		in, out := &in.Plans, &out.Plans
		*out = make([]InternalPlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalAPI.
func (in *InternalAPI) DeepCopy() *InternalAPI {
	if in == nil {
		return nil
	}
	out := new(InternalAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalApicastHosted) DeepCopyInto(out *InternalApicastHosted) {
	*out = *in
	in.APIcastBaseOptions.DeepCopyInto(&out.APIcastBaseOptions)
	if in.MappingRules != nil {
		in, out := &in.MappingRules, &out.MappingRules
		*out = make([]InternalMappingRule, len(*in))
		copy(*out, *in)
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]InternalPolicy, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalApicastHosted.
func (in *InternalApicastHosted) DeepCopy() *InternalApicastHosted {
	if in == nil {
		return nil
	}
	out := new(InternalApicastHosted)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalApicastOnPrem) DeepCopyInto(out *InternalApicastOnPrem) {
	*out = *in
	in.APIcastBaseOptions.DeepCopyInto(&out.APIcastBaseOptions)
	if in.MappingRules != nil {
		in, out := &in.MappingRules, &out.MappingRules
		*out = make([]InternalMappingRule, len(*in))
		copy(*out, *in)
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]InternalPolicy, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalApicastOnPrem.
func (in *InternalApicastOnPrem) DeepCopy() *InternalApicastOnPrem {
	if in == nil {
		return nil
	}
	out := new(InternalApicastOnPrem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalCodePlugin) DeepCopyInto(out *InternalCodePlugin) {
	*out = *in
	in.AuthenticationSettings.DeepCopyInto(&out.AuthenticationSettings)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalCodePlugin.
func (in *InternalCodePlugin) DeepCopy() *InternalCodePlugin {
	if in == nil {
		return nil
	}
	out := new(InternalCodePlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalCredentials) DeepCopyInto(out *InternalCredentials) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalCredentials.
func (in *InternalCredentials) DeepCopy() *InternalCredentials {
	if in == nil {
		return nil
	}
	out := new(InternalCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalIntegration) DeepCopyInto(out *InternalIntegration) {
	*out = *in
	if in.ApicastOnPrem != nil {
		in, out := &in.ApicastOnPrem, &out.ApicastOnPrem
		*out = new(InternalApicastOnPrem)
		(*in).DeepCopyInto(*out)
	}
	if in.CodePlugin != nil {
		in, out := &in.CodePlugin, &out.CodePlugin
		*out = new(InternalCodePlugin)
		(*in).DeepCopyInto(*out)
	}
	if in.ApicastHosted != nil {
		in, out := &in.ApicastHosted, &out.ApicastHosted
		*out = new(InternalApicastHosted)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalIntegration.
func (in *InternalIntegration) DeepCopy() *InternalIntegration {
	if in == nil {
		return nil
	}
	out := new(InternalIntegration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalLimit) DeepCopyInto(out *InternalLimit) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalLimit.
func (in *InternalLimit) DeepCopy() *InternalLimit {
	if in == nil {
		return nil
	}
	out := new(InternalLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalMappingRule) DeepCopyInto(out *InternalMappingRule) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalMappingRule.
func (in *InternalMappingRule) DeepCopy() *InternalMappingRule {
	if in == nil {
		return nil
	}
	out := new(InternalMappingRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalMetric) DeepCopyInto(out *InternalMetric) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalMetric.
func (in *InternalMetric) DeepCopy() *InternalMetric {
	if in == nil {
		return nil
	}
	out := new(InternalMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalPlan) DeepCopyInto(out *InternalPlan) {
	*out = *in
	out.Costs = in.Costs
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make([]InternalLimit, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalPlan.
func (in *InternalPlan) DeepCopy() *InternalPlan {
	if in == nil {
		return nil
	}
	out := new(InternalPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalPolicy) DeepCopyInto(out *InternalPolicy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalPolicy.
func (in *InternalPolicy) DeepCopy() *InternalPolicy {
	if in == nil {
		return nil
	}
	out := new(InternalPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Limit) DeepCopyInto(out *Limit) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Limit.
func (in *Limit) DeepCopy() *Limit {
	if in == nil {
		return nil
	}
	out := new(Limit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Limit) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimitBase) DeepCopyInto(out *LimitBase) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitBase.
func (in *LimitBase) DeepCopy() *LimitBase {
	if in == nil {
		return nil
	}
	out := new(LimitBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimitList) DeepCopyInto(out *LimitList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Limit, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitList.
func (in *LimitList) DeepCopy() *LimitList {
	if in == nil {
		return nil
	}
	out := new(LimitList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LimitList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimitObjectRef) DeepCopyInto(out *LimitObjectRef) {
	*out = *in
	out.Metric = in.Metric
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitObjectRef.
func (in *LimitObjectRef) DeepCopy() *LimitObjectRef {
	if in == nil {
		return nil
	}
	out := new(LimitObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimitPair) DeepCopyInto(out *LimitPair) {
	*out = *in
	out.A = in.A
	out.B = in.B
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitPair.
func (in *LimitPair) DeepCopy() *LimitPair {
	if in == nil {
		return nil
	}
	out := new(LimitPair)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimitSpec) DeepCopyInto(out *LimitSpec) {
	*out = *in
	out.LimitBase = in.LimitBase
	out.LimitObjectRef = in.LimitObjectRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitSpec.
func (in *LimitSpec) DeepCopy() *LimitSpec {
	if in == nil {
		return nil
	}
	out := new(LimitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimitStatus) DeepCopyInto(out *LimitStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitStatus.
func (in *LimitStatus) DeepCopy() *LimitStatus {
	if in == nil {
		return nil
	}
	out := new(LimitStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimitsDiff) DeepCopyInto(out *LimitsDiff) {
	*out = *in
	if in.MissingFromA != nil {
		in, out := &in.MissingFromA, &out.MissingFromA
		*out = make([]InternalLimit, len(*in))
		copy(*out, *in)
	}
	if in.MissingFromB != nil {
		in, out := &in.MissingFromB, &out.MissingFromB
		*out = make([]InternalLimit, len(*in))
		copy(*out, *in)
	}
	if in.Equal != nil {
		in, out := &in.Equal, &out.Equal
		*out = make([]InternalLimit, len(*in))
		copy(*out, *in)
	}
	if in.NotEqual != nil {
		in, out := &in.NotEqual, &out.NotEqual
		*out = make([]LimitPair, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitsDiff.
func (in *LimitsDiff) DeepCopy() *LimitsDiff {
	if in == nil {
		return nil
	}
	out := new(LimitsDiff)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MappingRule) DeepCopyInto(out *MappingRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MappingRule.
func (in *MappingRule) DeepCopy() *MappingRule {
	if in == nil {
		return nil
	}
	out := new(MappingRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MappingRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MappingRuleBase) DeepCopyInto(out *MappingRuleBase) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MappingRuleBase.
func (in *MappingRuleBase) DeepCopy() *MappingRuleBase {
	if in == nil {
		return nil
	}
	out := new(MappingRuleBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MappingRuleList) DeepCopyInto(out *MappingRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MappingRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MappingRuleList.
func (in *MappingRuleList) DeepCopy() *MappingRuleList {
	if in == nil {
		return nil
	}
	out := new(MappingRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MappingRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MappingRuleMetricRef) DeepCopyInto(out *MappingRuleMetricRef) {
	*out = *in
	out.MetricRef = in.MetricRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MappingRuleMetricRef.
func (in *MappingRuleMetricRef) DeepCopy() *MappingRuleMetricRef {
	if in == nil {
		return nil
	}
	out := new(MappingRuleMetricRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MappingRuleSpec) DeepCopyInto(out *MappingRuleSpec) {
	*out = *in
	out.MappingRuleBase = in.MappingRuleBase
	out.MappingRuleMetricRef = in.MappingRuleMetricRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MappingRuleSpec.
func (in *MappingRuleSpec) DeepCopy() *MappingRuleSpec {
	if in == nil {
		return nil
	}
	out := new(MappingRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MappingRuleStatus) DeepCopyInto(out *MappingRuleStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MappingRuleStatus.
func (in *MappingRuleStatus) DeepCopy() *MappingRuleStatus {
	if in == nil {
		return nil
	}
	out := new(MappingRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchLabels) DeepCopyInto(out *MatchLabels) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchLabels.
func (in *MatchLabels) DeepCopy() *MatchLabels {
	if in == nil {
		return nil
	}
	out := new(MatchLabels)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Metric) DeepCopyInto(out *Metric) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Metric.
func (in *Metric) DeepCopy() *Metric {
	if in == nil {
		return nil
	}
	out := new(Metric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Metric) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricList) DeepCopyInto(out *MetricList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Metric, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricList.
func (in *MetricList) DeepCopy() *MetricList {
	if in == nil {
		return nil
	}
	out := new(MetricList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MetricList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricPair) DeepCopyInto(out *MetricPair) {
	*out = *in
	out.A = in.A
	out.B = in.B
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricPair.
func (in *MetricPair) DeepCopy() *MetricPair {
	if in == nil {
		return nil
	}
	out := new(MetricPair)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricSpec) DeepCopyInto(out *MetricSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricSpec.
func (in *MetricSpec) DeepCopy() *MetricSpec {
	if in == nil {
		return nil
	}
	out := new(MetricSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricStatus) DeepCopyInto(out *MetricStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricStatus.
func (in *MetricStatus) DeepCopy() *MetricStatus {
	if in == nil {
		return nil
	}
	out := new(MetricStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsDiff) DeepCopyInto(out *MetricsDiff) {
	*out = *in
	if in.MissingFromA != nil {
		in, out := &in.MissingFromA, &out.MissingFromA
		*out = make([]InternalMetric, len(*in))
		copy(*out, *in)
	}
	if in.MissingFromB != nil {
		in, out := &in.MissingFromB, &out.MissingFromB
		*out = make([]InternalMetric, len(*in))
		copy(*out, *in)
	}
	if in.Equal != nil {
		in, out := &in.Equal, &out.Equal
		*out = make([]InternalMetric, len(*in))
		copy(*out, *in)
	}
	if in.NotEqual != nil {
		in, out := &in.NotEqual, &out.NotEqual
		*out = make([]MetricPair, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsDiff.
func (in *MetricsDiff) DeepCopy() *MetricsDiff {
	if in == nil {
		return nil
	}
	out := new(MetricsDiff)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenIDConnector) DeepCopyInto(out *OpenIDConnector) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenIDConnector.
func (in *OpenIDConnector) DeepCopy() *OpenIDConnector {
	if in == nil {
		return nil
	}
	out := new(OpenIDConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Plan) DeepCopyInto(out *Plan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Plan.
func (in *Plan) DeepCopy() *Plan {
	if in == nil {
		return nil
	}
	out := new(Plan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Plan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlanBase) DeepCopyInto(out *PlanBase) {
	*out = *in
	out.Costs = in.Costs
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlanBase.
func (in *PlanBase) DeepCopy() *PlanBase {
	if in == nil {
		return nil
	}
	out := new(PlanBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlanCost) DeepCopyInto(out *PlanCost) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlanCost.
func (in *PlanCost) DeepCopy() *PlanCost {
	if in == nil {
		return nil
	}
	out := new(PlanCost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlanList) DeepCopyInto(out *PlanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Plan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlanList.
func (in *PlanList) DeepCopy() *PlanList {
	if in == nil {
		return nil
	}
	out := new(PlanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlanPair) DeepCopyInto(out *PlanPair) {
	*out = *in
	in.A.DeepCopyInto(&out.A)
	in.B.DeepCopyInto(&out.B)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlanPair.
func (in *PlanPair) DeepCopy() *PlanPair {
	if in == nil {
		return nil
	}
	out := new(PlanPair)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlanSelectors) DeepCopyInto(out *PlanSelectors) {
	*out = *in
	in.LimitSelector.DeepCopyInto(&out.LimitSelector)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlanSelectors.
func (in *PlanSelectors) DeepCopy() *PlanSelectors {
	if in == nil {
		return nil
	}
	out := new(PlanSelectors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlanSpec) DeepCopyInto(out *PlanSpec) {
	*out = *in
	out.PlanBase = in.PlanBase
	in.PlanSelectors.DeepCopyInto(&out.PlanSelectors)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlanSpec.
func (in *PlanSpec) DeepCopy() *PlanSpec {
	if in == nil {
		return nil
	}
	out := new(PlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlanStatus) DeepCopyInto(out *PlanStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlanStatus.
func (in *PlanStatus) DeepCopy() *PlanStatus {
	if in == nil {
		return nil
	}
	out := new(PlanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlansDiff) DeepCopyInto(out *PlansDiff) {
	*out = *in
	if in.MissingFromA != nil {
		in, out := &in.MissingFromA, &out.MissingFromA
		*out = make([]InternalPlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MissingFromB != nil {
		in, out := &in.MissingFromB, &out.MissingFromB
		*out = make([]InternalPlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Equal != nil {
		in, out := &in.Equal, &out.Equal
		*out = make([]InternalPlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NotEqual != nil {
		in, out := &in.NotEqual, &out.NotEqual
		*out = make([]PlanPair, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlansDiff.
func (in *PlansDiff) DeepCopy() *PlansDiff {
	if in == nil {
		return nil
	}
	out := new(PlansDiff)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tenant) DeepCopyInto(out *Tenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tenant.
func (in *Tenant) DeepCopy() *Tenant {
	if in == nil {
		return nil
	}
	out := new(Tenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Tenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantList) DeepCopyInto(out *TenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Tenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantList.
func (in *TenantList) DeepCopy() *TenantList {
	if in == nil {
		return nil
	}
	out := new(TenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantSpec) DeepCopyInto(out *TenantSpec) {
	*out = *in
	out.TenantSecretRef = in.TenantSecretRef
	out.AdminPasswordRef = in.AdminPasswordRef
	out.MasterCredentialsRef = in.MasterCredentialsRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantSpec.
func (in *TenantSpec) DeepCopy() *TenantSpec {
	if in == nil {
		return nil
	}
	out := new(TenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantStatus) DeepCopyInto(out *TenantStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantStatus.
func (in *TenantStatus) DeepCopy() *TenantStatus {
	if in == nil {
		return nil
	}
	out := new(TenantStatus)
	in.DeepCopyInto(out)
	return out
}
