apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-redis
  labels:
    app: backend-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-redis
  template:
    metadata:
      labels:
        app: backend-redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - mountPath: /data
              name: redis-storage
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: backend-redis-pvc
