apiVersion: v1
kind: Secret
metadata:
  name: backend-redis
stringData:
  REDIS_QUEUES_SENTINEL_HOSTS: ""
  REDIS_QUEUES_SENTINEL_ROLE: ""
  REDIS_QUEUES_URL: redis://backend-redis.$(NAMESPACE).svc.cluster.local:6379/1
  REDIS_STORAGE_SENTINEL_HOSTS: ""
  REDIS_STORAGE_SENTINEL_ROLE: ""
  REDIS_STORAGE_URL: redis://backend-redis.$(NAMESPACE).svc.cluster.local:6379/2
type: Opaque