apiVersion: v1
kind: Service
metadata:
  name: backend-redis
  labels:
    app: backend-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: backend-redis
  type: ClusterIP