apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: 3scale-api-management
    control-plane: controller-manager
  name: threescale-operator-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app: 3scale-api-management
    control-plane: controller-manager
status:
  loadBalancer: {}
