apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: 3scale-api-management
  name: threescale-operator-webhook-service
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    app: 3scale-api-management
    control-plane: controller-manager
status:
  loadBalancer: {}
