apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: threescale-operator-manager-role
rules:
- apiGroups:
  - apps.3scale.net
  resources:
  - apimanagerbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.3scale.net
  resources:
  - apimanagerbackups/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.3scale.net
  resources:
  - apimanagerbackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps.3scale.net
  resources:
  - apimanagerrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.3scale.net
  resources:
  - apimanagerrestores/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.3scale.net
  resources:
  - apimanagerrestores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capabilities.3scale.net
  resources:
  - activedocs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capabilities.3scale.net
  resources:
  - activedocs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - capabilities.3scale.net
  resources:
  - backends
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capabilities.3scale.net
  resources:
  - backends/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capabilities.3scale.net
  resources:
  - backends/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - capabilities.3scale.net
  resources:
  - custompolicydefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capabilities.3scale.net
  resources:
  - custompolicydefinitions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - capabilities.3scale.net
  resources:
  - developeraccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capabilities.3scale.net
  resources:
  - developeraccounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - capabilities.3scale.net
  resources:
  - developerusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capabilities.3scale.net
  resources:
  - developerusers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - capabilities.3scale.net
  resources:
  - openapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capabilities.3scale.net
  resources:
  - openapis/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capabilities.3scale.net
  resources:
  - openapis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - capabilities.3scale.net
  resources:
  - products
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capabilities.3scale.net
  resources:
  - products/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capabilities.3scale.net
  resources:
  - products/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - capabilities.3scale.net
  resources:
  - tenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capabilities.3scale.net
  resources:
  - tenants/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capabilities.3scale.net
  resources:
  - tenants/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
