apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app: 3scale-api-management
  name: threescale-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
