apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: system-postgresql-pvc
  labels:
    app: system-postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi