apiVersion: v1
kind: Secret
metadata:
  name: system-database
stringData:
  DB_USER: myuser
  DB_PASSWORD: password
  URL: postgresql://myuser:password@system-postgresql.$(NAMESPACE).svc.cluster.local/dev
type: Opaque