apiVersion: v1
kind: Template
metadata:
  name: "amp-build"
message: "AMP BuildConfig Template"
objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
      app: zync
    name: ruby-25-ubi7
  spec:
    tags:
    - from:
        kind: DockerImage
        name: registry.redhat.io/ubi7/ruby-25
      name: latest

- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: zync
    name: zync
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: "amp-zync:${IMAGESTREAM_TAG_NAME}"
    source:
      git:
        uri: https://github.com/3scale/zync.git
        ref: "${ZYNC_GIT_REF}"
      type: Git
    strategy:
      dockerStrategy:
        pullSecret:
          name: "${PULLSECRET_NAME}"
        from:
          kind: ImageStreamTag
          name: ruby-25-ubi7:latest
      type: Docker

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: system
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: "amp-system:${IMAGESTREAM_TAG_NAME}"
    source:
      git:
        uri: "https://github.com/3scale/porta.git"
        ref: "${PORTA_GIT_REF}"
      type: "Git"
    strategy:
      type: Docker
      dockerStrategy:
        pullSecret:
          name: "${PULLSECRET_NAME}"
        dockerfilePath: openshift/system/Dockerfile.on_prem
        forcePull: true

- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: apicast
    name: apicast
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: "amp-apicast:${IMAGESTREAM_TAG_NAME}"
    source:
      contextDir: gateway
      git:
        uri: https://github.com/3scale/apicast.git
        ref: "${APICAST_GIT_REF}"
      type: Git
    strategy:
      sourceStrategy:
        forcePull: true
        from:
          kind: ImageStreamTag
          name: s2i-openresty-centos7:builder
        runtimeImage:
          kind: ImageStreamTag
          name: s2i-openresty-centos7:runtime
      type: Source

- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: apicast
    name: s2i-openresty-centos7
  spec:
    tags:
    - from:
        kind: DockerImage
        name: quay.io/3scale/s2i-openresty-centos7:master
      name: builder
      importPolicy:
        scheduled: true
    - from:
        kind: DockerImage
        name: quay.io/3scale/s2i-openresty-centos7:master-runtime
      name: runtime
      importPolicy:
        scheduled: true

- apiVersion: v1
  kind: BuildConfig
  metadata:
      name: backend
  spec:
      output:
          to:
              kind: ImageStreamTag
              name: "amp-backend:${IMAGESTREAM_TAG_NAME}"
      source:
          git:
              uri: "https://github.com/3scale/apisonator.git"
              ref: "${APISONATOR_GIT_REF}"
          type: Git
      strategy:
          type: Docker
          dockerStrategy:
              pullSecret:
                  name: "${PULLSECRET_NAME}"
              contextDir: /
              dockerfilePath: openshift/distro/centos/7/release/Dockerfile

parameters:
- name: ZYNC_GIT_REF
  description: "Zync git reference to use. Can be a tag or branch."
  value: "master"
  required: true
- name: PORTA_GIT_REF
  description: "Porta git reference to use. Can be a tag or branch."
  value: "master"
  required: true
- name: APICAST_GIT_REF
  description: "Apicast git reference to use. Can be a tag or branch."
  value: "master"
  required: true
- name: APISONATOR_GIT_REF
  description: "Apisonator git reference to use. Can be a tag or branch."
  value: "master"
  required: true
- name: IMAGESTREAM_TAG_NAME
  description: "Value of the ImageStream tags to be used"
  value: "latest"
  required: true
- name: PULLSECRET_NAME
  description: PullSecret is the name of a Secret that would be used for setting up the authentication for pulling the Docker images from the private Docker egistries 
  value: "threescale-registry-auth"
  required: true
