apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
  labels:
    app: zync
  name: zync
spec:
  output:
    to:
      kind: ImageStreamTag
      name: amp-zync:latest
  source:
    git:
      uri: https://github.com/3scale/zync.git
      ref: "master"
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: ruby-24-centos7:latest
    type: Docker
  triggers:
  - type: ConfigChange
