---
version: 2.1

parameters:
  memcached_image:
    type: string
    default: "memcached:1.5"
  components_tag_name:
    type: string
    default: "latest"
  components_imagestream_tag_name:
    type: string
    default: "master"

##################################### YAML ANCHORS  ############################################

tag-trigger: &tag-trigger
  tags:
    only: /^v.*/

only-master-filter: &only-master-filter
  filters:
    branches:
      only: master

nightly-trigger: &nightly-trigger
  triggers:
    - schedule:
        cron: "0 0 * * *"
        <<: *only-master-filter

commands:
  attach-workspace:
    steps:
    - run:
        name: Preparing workspace directory
        command: |
          sudo rm -rf /tmp/workspace
          sudo mkdir -p /tmp/workspace
          sudo chown -vf circleci:circleci /tmp/workspace
        working_directory: /
    - attach_workspace:
        at: /tmp/workspace

  docker-login:
    steps:
      - run:
          name: Docker login
          command: |
            docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}" "${DOCKER_REGISTRY}"

  install-operator-sdk:
    steps:
      - run:
          name: Install operator-sdk
          command: |
            export OPERATOR_SDK_RELEASE_VERSION=v1.2.0
            curl -OJL https://github.com/operator-framework/operator-sdk/releases/download/${OPERATOR_SDK_RELEASE_VERSION}/operator-sdk-${OPERATOR_SDK_RELEASE_VERSION}-x86_64-linux-gnu
            chmod +x operator-sdk-${OPERATOR_SDK_RELEASE_VERSION}-x86_64-linux-gnu && sudo cp operator-sdk-${OPERATOR_SDK_RELEASE_VERSION}-x86_64-linux-gnu /usr/local/bin/operator-sdk && rm operator-sdk-${OPERATOR_SDK_RELEASE_VERSION}-x86_64-linux-gnu

  install-dependencies:
    steps:
      - restore_cache:
          keys:
            - threescale-operator-go-mod-v2-{{ arch }}-{{ checksum "go.sum" }}
            # Find the most recently generated cache used from any branch
            - threescale-operator-go-mod-v2-{{ arch }}
      - run:
          name: Install go dependencies
          command: |
            make download
      - save_cache:
          key: threescale-operator-go-mod-v2-{{ arch }}-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

  build-operator-image:
    steps:
      - checkout
      - install-operator-sdk
      - install-dependencies
      - run:
          name: Build Operator
          command: |
              make docker-build-only IMG=172.30.1.1:5000/openshift/3scale-operator:test

  unit-tests:
    steps:
      - checkout
      - install-dependencies
      - run:
          name: Run unit tests
          command: |
            make test-unit
jobs:
  install-operator:
    docker:
      - image: cimg/go:1.18
    working_directory: ~/project/3scale-operator
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - build-operator-image
      - run:
          name: Sharing requirements to downstream job
          command: |
            mkdir -p /tmp/workspace/images
            docker save -o /tmp/workspace/images/3scaleoperator-image.tar 172.30.1.1:5000/openshift/3scale-operator:test
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - images/3scaleoperator-image.tar

  build-operator-image-only:
    docker:
      - image: cimg/go:1.18
    working_directory: ~/project/3scale-operator
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - build-operator-image

  tag-operator-image-master:
    machine:
      image: ubuntu-2004:202201-02
      docker_layer_caching: true
    steps:
      - attach-workspace
      - run:
          name: Unpack docker image
          command: |
            docker load -i /tmp/workspace/images/3scaleoperator-image.tar
      - run:
          name: Tag image as master
          command: |
              docker tag 172.30.1.1:5000/openshift/3scale-operator:test quay.io/3scale/3scale-operator:master
      - docker-login
      - run:
          name: Push master image
          command: |
              docker push quay.io/3scale/3scale-operator:master
      - run:
          name: Tag image as latest
          command: |
            docker tag quay.io/3scale/3scale-operator:master quay.io/3scale/3scale-operator:latest
      - run:
          name: Push latest image
          command: |
              docker push quay.io/3scale/3scale-operator:latest

  tag-operator-image-release:
    machine:
      image: ubuntu-2004:202201-02
      docker_layer_caching: true
    steps:
      - attach-workspace
      - run:
          name: Unpack docker image
          command: |
            docker load -i /tmp/workspace/images/3scaleoperator-image.tar
      - run:
          name: Tag image as release ${CIRCLE_TAG}
          command: |
              docker tag 172.30.1.1:5000/openshift/3scale-operator:test quay.io/3scale/3scale-operator:${CIRCLE_TAG}
      - docker-login
      - run:
          name: Push ${CIRCLE_TAG} tag
          command: |
              docker push quay.io/3scale/3scale-operator:${CIRCLE_TAG}

  run-unit-tests:
    docker:
      - image: cimg/go:1.18
    resource_class: large
    steps:
      - unit-tests
      - run:
          command: cat /sys/fs/cgroup/memory/memory.max_usage_in_bytes
          when: always

  test-crds:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - install-dependencies
      - run: make test-crds

  test-manifests-version:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - install-dependencies
      - run: make test-manifests-version
  license-check:
    docker:
      - image: cimg/go:1.18
    steps:
      - run:
          name: Installing ruby
          command: |
            # Determine if sudo is neccessary
            SUDO=""
            if [[ $EUID -ne 0 ]]; then
            SUDO=sudo
            fi
            # Install ruby
            $SUDO apt-get update --allow-releaseinfo-change && $SUDO apt-get install -y ruby-full
      - run:
          name: Installing License tool
          command: |
            # Determine if sudo is neccessary
            SUDO=""
            if [[ $EUID -ne 0 ]]; then
            SUDO=sudo
            fi
            # Install ruby
            $SUDO gem install license_finder --version 5.7.1
      - checkout
      - install-dependencies
      - run: make licenses-check

  unit-tests-coverage:
    docker:
      - image: cimg/go:1.18
    resource_class: large
    steps:
      - unit-tests
      - run:
          name: Report to Codecov
          command: |
            cp _output/unit.cov coverage.txt
            bash <(curl -s https://codecov.io/bash)

  bundle-validate:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - install-operator-sdk
      - run: make bundle
      - run: make bundle-update-test

  assets-validate:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - install-operator-sdk
      - run: make assets-update-test

  prometheusrules-validate:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run: make prometheusrules-update-test

  doc-toc-validate:
    docker:
      - image: cimg/base:2023.05
    steps:
      - checkout
      - run: make toc-user-guide
      - run: make toc-app-capabilities
      - run: make toc-apimanager-reference
      - run: make doc-update-test

workflows:
  version: 2
  operator:
    jobs:
      - license-check
      - test-crds
      - test-manifests-version
      - run-unit-tests
      - bundle-validate
      - assets-validate
      - prometheusrules-validate
      - build-operator-image-only
      - unit-tests-coverage:
          requires:
            - run-unit-tests
          <<: *only-master-filter
  nightly:
    jobs:
      - build-operator-image-only
    <<: *nightly-trigger
  operator-release:
    jobs:
      - install-operator:
          filters:
            <<: *tag-trigger
      - tag-operator-image-master:
          context: org-global
          requires:
            - install-operator
          filters:
            branches:
              only: master
      - tag-operator-image-release:
          context: org-global
          requires:
            - install-operator
          filters:
            <<: *tag-trigger
            branches:
              ignore: /.*/
