# permissions for end users to edit apimanagerrestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apimanagerrestore-editor-role
rules:
- apiGroups:
  - apps.3scale.net
  resources:
  - apimanagerrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.3scale.net
  resources:
  - apimanagerrestores/status
  verbs:
  - get
