# permissions for end users to view apimanagerrestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apimanagerrestore-viewer-role
rules:
- apiGroups:
  - apps.3scale.net
  resources:
  - apimanagerrestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.3scale.net
  resources:
  - apimanagerrestores/status
  verbs:
  - get
