# permissions for end users to edit apimanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apimanager-editor-role
rules:
- apiGroups:
  - apps.3scale.net.3scale.net
  resources:
  - apimanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.3scale.net.3scale.net
  resources:
  - apimanagers/status
  verbs:
  - get
