# permissions for end users to edit apimanagerbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apimanagerbackup-editor-role
rules:
- apiGroups:
  - apps.3scale.net
  resources:
  - apimanagerbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.3scale.net
  resources:
  - apimanagerbackups/status
  verbs:
  - get
