# permissions for end users to edit applicationauths.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: applicationauth-editor-role
rules:
- apiGroups:
  - capabilities.3scale.net
  resources:
  - applicationauths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capabilities.3scale.net
  resources:
  - applicationauths/status
  verbs:
  - get
