# permissions for end users to view applicationauths.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: applicationauth-viewer-role
rules:
- apiGroups:
  - capabilities.3scale.net
  resources:
  - applicationauths
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - capabilities.3scale.net
  resources:
  - applicationauths/status
  verbs:
  - get
