# permissions for end users to edit custompolicydefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custompolicydefinition-editor-role
rules:
- apiGroups:
  - capabilities.3scale.net
  resources:
  - custompolicydefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capabilities.3scale.net
  resources:
  - custompolicydefinitions/status
  verbs:
  - get
