# permissions for end users to view custompolicydefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custompolicydefinition-viewer-role
rules:
- apiGroups:
  - capabilities.3scale.net
  resources:
  - custompolicydefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - capabilities.3scale.net
  resources:
  - custompolicydefinitions/status
  verbs:
  - get
