# permissions for end users to view developeraccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developeraccount-viewer-role
rules:
- apiGroups:
  - capabilities.3scale.net
  resources:
  - developeraccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - capabilities.3scale.net
  resources:
  - developeraccounts/status
  verbs:
  - get
