# permissions for end users to edit developeraccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developeraccount-editor-role
rules:
- apiGroups:
  - capabilities.3scale.net
  resources:
  - developeraccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capabilities.3scale.net
  resources:
  - developeraccounts/status
  verbs:
  - get
