# permissions for end users to edit developerusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developeruser-editor-role
rules:
- apiGroups:
  - capabilities.3scale.net
  resources:
  - developerusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capabilities.3scale.net
  resources:
  - developerusers/status
  verbs:
  - get
