# permissions for end users to view developerusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developeruser-viewer-role
rules:
- apiGroups:
  - capabilities.3scale.net
  resources:
  - developerusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - capabilities.3scale.net
  resources:
  - developerusers/status
  verbs:
  - get
