# permissions for end users to view openapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openapi-viewer-role
rules:
- apiGroups:
  - capabilities.3scale.net
  resources:
  - openapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - capabilities.3scale.net
  resources:
  - openapis/status
  verbs:
  - get
