# permissions for end users to edit openapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openapi-editor-role
rules:
- apiGroups:
  - capabilities.3scale.net
  resources:
  - openapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capabilities.3scale.net
  resources:
  - openapis/status
  verbs:
  - get
