# permissions for end users to edit policyregistries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: policyregistry-editor-role
rules:
- apiGroups:
  - capabilities.3scale.net
  resources:
  - policyregistries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capabilities.3scale.net
  resources:
  - policyregistries/status
  verbs:
  - get
