# permissions for end users to edit promoteproducts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promoteproduct-editor-role
rules:
- apiGroups:
  - capabilities.3scale.net
  resources:
  - promoteproducts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capabilities.3scale.net
  resources:
  - promoteproducts/status
  verbs:
  - get
