# permissions for end users to view proxyconfigpromotes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proxyconfigpromote-viewer-role
rules:
- apiGroups:
  - capabilities.3scale.net
  resources:
  - proxyconfigpromotes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - capabilities.3scale.net
  resources:
  - proxyconfigpromotes/status
  verbs:
  - get
