# permissions for end users to edit tenants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenant-editor-role
rules:
- apiGroups:
  - capabilities.3scale.net
  resources:
  - tenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capabilities.3scale.net
  resources:
  - tenants/status
  verbs:
  - get
