apiVersion: amp.3scale.net/v1alpha1
kind: AMP
metadata:
  name: example-amp
spec:
  # Add fields here
  ampRelease: "2.4"
  wildcardDomain: msoriano.127.0.0.1.nip.io
  productized: false
  evaluation: true
  s3version: false
  haversion: false
