apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: amps.amp.3scale.net
spec:
  group: amp.3scale.net
  names:
    kind: AMP
    listKind: AMPList
    plural: amps
    singular: amp
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            ampRelease:
              type: string
            wildcardDomain:
              type: string
          required:
            - ampRelease
            - wildcardDomain
