apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apimanagerbackups.apps.3scale.net
spec:
  group: apps.3scale.net
  names:
    kind: APIManagerBackup
    listKind: APIManagerBackupList
    plural: apimanagerbackups
    singular: apimanagerbackup
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: APIManagerBackup is the Schema for the apimanagerbackups API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: APIManagerBackupSpec defines the desired state of APIManagerBackup
          properties:
            backupDestination:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              properties:
                persistentVolumeClaim:
                  description: 'Ways to define a PVC creation: Define VolumeName OR
                    Define Resources. When VolumeName is specified resources is not
                    needed: Detailed info: https://docs.okd.io/3.11/dev_guide/persistent_volumes.html#persistent-volumes-volumes-and-claim-prebinding'
                  properties:
                    resources:
                      properties:
                        requests:
                          type: string
                      required:
                      - requests
                      type: object
                    storageClass:
                      type: string
                    volumeName:
                      type: string
                  type: object
              type: object
          required:
          - backupDestination
          type: object
        status:
          description: APIManagerBackupStatus defines the observed state of APIManagerBackup
          properties:
            apiManagerSourceName:
              type: string
            backupPersistentVolumeClaimName:
              type: string
            completed:
              type: boolean
            completionTime:
              format: date-time
              type: string
            conditions:
              description: Represents the latest available observations of an APIManagerBackup's
                current state.
              items:
                description: APIManagerBackupCondition describes the state of an APIManagerBackup
                  at a certain point.
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another.
                    format: date-time
                    type: string
                  message:
                    description: A human readable message indicating details about
                      the transition.
                    type: string
                  reason:
                    description: The reason for the condition's last transition.
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown
                    type: string
                  type:
                    description: Type of APIManagerBackup condition
                    type: string
                required:
                - status
                - type
                type: object
              type: array
            startTime:
              format: date-time
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
