apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: example-apimanager
spec:
  wildcardDomain: example.com
  apicast:
    image: "quay.io/3scale/apicast:nightly"
  backend:
    image: "quay.io/3scale/apisonator:nightly"
  system:
    image: "quay.io/3scale/porta:nightly"
  zync:
    image: "quay.io/3scale/zync:nightly"
