apiVersion: apiextensions.k8s.io/v1beta1
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: apimanagers.apps.3scale.net
spec:
  group: apps.3scale.net
  names:
    kind: APIManager
    listKind: APIManagerList
    plural: apimanagers
    singular: apimanager
  scope: Namespaced
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            apicast:
              properties:
                image:
                  type: string
                mananagementAPI:
                  type: string
                openSSLVerify:
                  type: boolean
                registryURL:
                  type: string
                responseCodes:
                  type: boolean
              type: object
            appLabel:
              type: string
            backend:
              properties:
                image:
                  type: string
                redisImage:
                  type: string
              type: object
            highAvailability:
              properties:
                enabled:
                  type: boolean
              type: object
            imageStreamTagImportInsecure:
              type: boolean
            productVersion:
              type: string
            system:
              properties:
                database:
                  properties:
                    mysql:
                      properties:
                        image:
                          type: string
                      type: object
                  type: object
                fileStorage:
                  properties:
                    persistentVolumeClaim:
                      properties:
                        storageClassName:
                          type: string
                      type: object
                    sthree:
                      properties:
                        awsBucket:
                          type: string
                        awsCredentialsSecret:
                          type: object
                        awsRegion:
                          type: string
                        fileUploadStorage:
                          type: string
                      required:
                      - awsBucket
                      - awsRegion
                      - awsCredentialsSecret
                      - fileUploadStorage
                      type: object
                  type: object
                image:
                  type: string
                memcachedImage:
                  type: string
                redisImage:
                  type: string
              type: object
            tenantName:
              type: string
            wildcardDomain:
              type: string
            wildcardPolicy:
              type: string
            wildcardRouter:
              properties:
                image:
                  type: string
              type: object
            zync:
              properties:
                image:
                  type: string
                postgreSQLImage:
                  type: string
              type: object
          required:
          - productVersion
          - wildcardDomain
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
          type: object
