apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: limits.capabilities.3scale.net
spec:
  group: capabilities.3scale.net
  names:
    kind: Limit
    listKind: LimitList
    plural: limits
    singular: limit
  scope: Namespaced
  version: v1alpha1
