apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: limits.capabilities.3scale.net
spec:
  group: capabilities.3scale.net
  names:
    kind: Limit
    listKind: LimitList
    plural: limits
    singular: limit
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            maxValue:
              format: int64
              type: integer
            metricRef:
              type: object
            period:
              type: string
          required:
          - period
          - maxValue
          - metricRef
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
