apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: bindings.capabilities.3scale.net
spec:
  group: capabilities.3scale.net
  names:
    kind: Binding
    listKind: BindingList
    plural: bindings
    singular: binding
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            APISelector:
              type: object
            credentialsRef:
              type: object
          required:
          - credentialsRef
          type: object
        status:
          properties:
            currentState:
              type: string
            desiredState:
              type: string
            lastSync:
              type: object
            previousState:
              type: string
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
