apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backends.capabilities.3scale.net
spec:
  group: capabilities.3scale.net
  names:
    kind: Backend
    listKind: BackendList
    plural: backends
    singular: backend
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Backend is the Schema for the backends API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: BackendSpec defines the desired state of Backend
          properties:
            description:
              type: string
            mappingRules:
              items:
                description: MappingRuleSpec defines the desired state of Product's
                  MappingRule
                properties:
                  httpMethod:
                    enum:
                    - GET
                    - HEAD
                    - POST
                    - PUT
                    - DELETE
                    - OPTIONS
                    - TRACE
                    - PATCH
                    - CONNECT
                    type: string
                  increment:
                    type: integer
                  metricMethodRef:
                    type: string
                  pattern:
                    type: string
                  position:
                    type: integer
                required:
                - httpMethod
                - metricMethodRef
                - pattern
                type: object
              type: array
            methods:
              additionalProperties:
                description: Methodpec defines the desired state of Product's Method
                properties:
                  description:
                    type: string
                  friendlyName:
                    type: string
                required:
                - friendlyName
                type: object
              description: 'Methods Map: system_name -> MethodSpec system_name attr
                is unique for all metrics AND methods In other words, if metric''s
                system_name is A, there is no metric or method with system_name A.'
              type: object
            metrics:
              additionalProperties:
                description: MetricSpec defines the desired state of Product's Metric
                properties:
                  description:
                    type: string
                  friendlyName:
                    type: string
                  unit:
                    type: string
                required:
                - friendlyName
                - unit
                type: object
              description: 'Metrics Map: system_name -> MetricSpec system_name attr
                is unique for all metrics AND methods In other words, if metric''s
                system_name is A, there is no metric or method with system_name A.'
              type: object
            name:
              description: Name is human readable name for the backend
              type: string
            privateBaseURL:
              pattern: ^https?:\/\/.*$
              type: string
            providerAccountRef:
              description: ProviderAccountRef references account provider credentials
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            systemName:
              description: SystemName identifies uniquely the product within the account
                provider Default value will be sanitized Name
              type: string
          required:
          - name
          type: object
        status:
          description: BackendStatus defines the observed state of Backend
          properties:
            backendId:
              format: int64
              type: integer
            conditions:
              description: Current state of the 3scale backend. Conditions represent
                the latest available observations of an object's state
              items:
                description: "Condition represents an observation of an object's state.
                  Conditions are an extension mechanism intended to be used when the
                  details of an observation are not a priori known or would not apply
                  to all instances of a given Kind. \n Conditions should be added
                  to explicitly convey properties that users and components care about
                  rather than requiring those properties to be inferred from other
                  observations. Once defined, the meaning of a Condition can not be
                  changed arbitrarily - it becomes part of the API, and has the same
                  backwards- and forwards-compatibility concerns of any other part
                  of the API."
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    description: ConditionReason is intended to be a one-word, CamelCase
                      representation of the category of cause of the current status.
                      It is intended to be used in concise output, such as one-line
                      kubectl get output, and in summarizing occurrences of causes.
                    type: string
                  status:
                    type: string
                  type:
                    description: "ConditionType is the type of the condition and is
                      typically a CamelCased word or short phrase. \n Condition types
                      should indicate state in the \"abnormal-true\" polarity. For
                      example, if the condition indicates when a policy is invalid,
                      the \"is valid\" case is probably the norm, so the condition
                      should be called \"Invalid\"."
                    type: string
                required:
                - status
                - type
                type: object
              type: array
            errorMessage:
              type: string
            errorReason:
              description: "In the event that there is a terminal problem reconciling
                the replicas, both ErrorReason and ErrorMessage will be set. ErrorReason
                will be populated with a succinct value suitable for machine interpretation,
                while ErrorMessage will contain a more verbose string suitable for
                logging and human consumption. \n These fields should not be set for
                transitive errors that a controller faces that are expected to be
                fixed automatically over time (like service outages), but instead
                indicate that something is fundamentally wrong with the Backend's
                spec or the configuration of the backend controller, and that manual
                intervention is required. Examples of terminal errors would be invalid
                combinations of settings in the spec, values that are unsupported
                by the backend controller, or the responsible backend controller itself
                being critically misconfigured. \n Any transient errors that occur
                during the reconciliation of Backends can be added as events to the
                Backend's object and/or logged in the controller's output."
              type: string
            observedGeneration:
              description: ObservedGeneration reflects the generation of the most
                recently observed MachineSet.
              format: int64
              type: integer
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
