apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: tenants.capabilities.3scale.net
spec:
  group: capabilities.3scale.net
  names:
    kind: Tenant
    listKind: TenantList
    plural: tenants
    singular: tenant
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            email:
              type: string
            masterCredentialsRef:
              type: object
            organizationName:
              type: string
            passwordCredentialsRef:
              type: object
            systemMasterUrl:
              type: string
            tenantSecretRef:
              type: object
            username:
              type: string
          required:
          - username
          - email
          - organizationName
          - systemMasterUrl
          - tenantSecretRef
          - passwordCredentialsRef
          - masterCredentialsRef
          type: object
        status:
          properties:
            adminID:
              format: int64
              type: integer
            tenantID:
              format: int64
              type: integer
          required:
          - tenantID
          - adminID
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
