apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bindings.capabilities.3scale.net
spec:
  group: capabilities.3scale.net
  names:
    kind: Binding
    listKind: BindingList
    plural: bindings
    singular: binding
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Binding is the Schema for the bindings API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: BindingSpec defines the desired state of Binding
          properties:
            apiSelector:
              description: A label selector is a label query over a set of resources.
                The result of matchLabels and matchExpressions are ANDed. An empty
                label selector matches all objects. A null label selector matches
                no objects.
              properties:
                matchExpressions:
                  description: matchExpressions is a list of label selector requirements.
                    The requirements are ANDed.
                  items:
                    description: A label selector requirement is a selector that contains
                      values, a key, and an operator that relates the key and values.
                    properties:
                      key:
                        description: key is the label key that the selector applies
                          to.
                        type: string
                      operator:
                        description: operator represents a key's relationship to a
                          set of values. Valid operators are In, NotIn, Exists and
                          DoesNotExist.
                        type: string
                      values:
                        description: values is an array of string values. If the operator
                          is In or NotIn, the values array must be non-empty. If the
                          operator is Exists or DoesNotExist, the values array must
                          be empty. This array is replaced during a strategic merge
                          patch.
                        items:
                          type: string
                        type: array
                    required:
                    - key
                    - operator
                    type: object
                  type: array
                matchLabels:
                  additionalProperties:
                    type: string
                  description: matchLabels is a map of {key,value} pairs. A single
                    {key,value} in the matchLabels map is equivalent to an element
                    of matchExpressions, whose key field is "key", the operator is
                    "In", and the values array contains only "value". The requirements
                    are ANDed.
                  type: object
              type: object
            credentialsRef:
              description: SecretReference represents a Secret Reference. It has enough
                information to retrieve secret in any namespace
              properties:
                name:
                  description: Name is unique within a namespace to reference a secret
                    resource.
                  type: string
                namespace:
                  description: Namespace defines the space within which the secret
                    name must be unique.
                  type: string
              type: object
          required:
          - credentialsRef
          type: object
        status:
          description: BindingStatus defines the observed state of Binding
          properties:
            currentState:
              type: string
            desiredState:
              type: string
            lastSync:
              description: Timestamp is a struct that is equivalent to Time, but intended
                for protobuf marshalling/unmarshalling. It is generated into a serialization
                that matches Time. Do not use in Go structs.
              properties:
                nanos:
                  description: Non-negative fractions of a second at nanosecond resolution.
                    Negative second values with fractions must still have non-negative
                    nanos values that count forward in time. Must be from 0 to 999,999,999
                    inclusive. This field may be limited in precision depending on
                    context.
                  format: int32
                  type: integer
                seconds:
                  description: Represents seconds of UTC time since Unix epoch 1970-01-01T00:00:00Z.
                    Must be from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59Z inclusive.
                  format: int64
                  type: integer
              required:
              - nanos
              - seconds
              type: object
            previousState:
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
