apiVersion: capabilities.3scale.net/v1beta1
kind: OpenAPI
metadata:
  name: example-openapi
spec:
  openapiRef:
    url: "https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml"
