apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apis.capabilities.3scale.net
spec:
  group: capabilities.3scale.net
  names:
    kind: API
    listKind: APIList
    plural: apis
    singular: api
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            description:
              type: string
            integrationMethod:
              properties:
                apicastHosted:
                  properties:
                    apiTestGetRequest:
                      type: string
                    authenticationSettings:
                      properties:
                        credentials:
                          properties:
                            apiKey:
                              properties:
                                authParameterName:
                                  type: string
                                credentialsLocation:
                                  type: string
                              required:
                              - authParameterName
                              - credentialsLocation
                              type: object
                            appID:
                              properties:
                                appIDParameterName:
                                  type: string
                                appKeyParameterName:
                                  type: string
                                credentialsLocation:
                                  type: string
                              required:
                              - appIDParameterName
                              - appKeyParameterName
                              - credentialsLocation
                              type: object
                            openIDConnector:
                              properties:
                                credentialsLocation:
                                  type: string
                                issuer:
                                  type: string
                              required:
                              - issuer
                              - credentialsLocation
                              type: object
                          type: object
                        errors:
                          properties:
                            authenticationFailed:
                              properties:
                                contentType:
                                  type: string
                                responseBody:
                                  type: string
                                responseCode:
                                  format: int64
                                  type: integer
                              required:
                              - responseCode
                              - contentType
                              - responseBody
                              type: object
                            authenticationMissing:
                              properties:
                                contentType:
                                  type: string
                                responseBody:
                                  type: string
                                responseCode:
                                  format: int64
                                  type: integer
                              required:
                              - responseCode
                              - contentType
                              - responseBody
                              type: object
                          required:
                          - authenticationFailed
                          - authenticationMissing
                          type: object
                        hostHeader:
                          type: string
                        secretToken:
                          type: string
                      required:
                      - hostHeader
                      - secretToken
                      - credentials
                      - errors
                      type: object
                    mappingRulesSelector:
                      type: object
                    policiesSelector:
                      type: object
                    privateBaseURL:
                      type: string
                  required:
                  - privateBaseURL
                  - apiTestGetRequest
                  - authenticationSettings
                  type: object
                apicastOnPrem:
                  properties:
                    apiTestGetRequest:
                      type: string
                    authenticationSettings:
                      properties:
                        credentials:
                          properties:
                            apiKey:
                              properties:
                                authParameterName:
                                  type: string
                                credentialsLocation:
                                  type: string
                              required:
                              - authParameterName
                              - credentialsLocation
                              type: object
                            appID:
                              properties:
                                appIDParameterName:
                                  type: string
                                appKeyParameterName:
                                  type: string
                                credentialsLocation:
                                  type: string
                              required:
                              - appIDParameterName
                              - appKeyParameterName
                              - credentialsLocation
                              type: object
                            openIDConnector:
                              properties:
                                credentialsLocation:
                                  type: string
                                issuer:
                                  type: string
                              required:
                              - issuer
                              - credentialsLocation
                              type: object
                          type: object
                        errors:
                          properties:
                            authenticationFailed:
                              properties:
                                contentType:
                                  type: string
                                responseBody:
                                  type: string
                                responseCode:
                                  format: int64
                                  type: integer
                              required:
                              - responseCode
                              - contentType
                              - responseBody
                              type: object
                            authenticationMissing:
                              properties:
                                contentType:
                                  type: string
                                responseBody:
                                  type: string
                                responseCode:
                                  format: int64
                                  type: integer
                              required:
                              - responseCode
                              - contentType
                              - responseBody
                              type: object
                          required:
                          - authenticationFailed
                          - authenticationMissing
                          type: object
                        hostHeader:
                          type: string
                        secretToken:
                          type: string
                      required:
                      - hostHeader
                      - secretToken
                      - credentials
                      - errors
                      type: object
                    mappingRulesSelector:
                      type: object
                    policiesSelector:
                      type: object
                    privateBaseURL:
                      type: string
                    productionPublicBaseURL:
                      type: string
                    stagingPublicBaseURL:
                      type: string
                  required:
                  - privateBaseURL
                  - apiTestGetRequest
                  - authenticationSettings
                  - stagingPublicBaseURL
                  - productionPublicBaseURL
                  type: object
                codePlugin:
                  properties:
                    authenticationSettings:
                      properties:
                        credentials:
                          properties:
                            apiKey:
                              properties:
                                authParameterName:
                                  type: string
                                credentialsLocation:
                                  type: string
                              required:
                              - authParameterName
                              - credentialsLocation
                              type: object
                            appID:
                              properties:
                                appIDParameterName:
                                  type: string
                                appKeyParameterName:
                                  type: string
                                credentialsLocation:
                                  type: string
                              required:
                              - appIDParameterName
                              - appKeyParameterName
                              - credentialsLocation
                              type: object
                            openIDConnector:
                              properties:
                                credentialsLocation:
                                  type: string
                                issuer:
                                  type: string
                              required:
                              - issuer
                              - credentialsLocation
                              type: object
                          type: object
                      required:
                      - credentials
                      type: object
                  required:
                  - authenticationSettings
                  type: object
              type: object
            metricSelector:
              type: object
            planSelector:
              type: object
          required:
          - description
          - integrationMethod
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
