apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: 3scale-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: APIManager is the Schema for the apimanagers API
      displayName: APIManager
      kind: APIManager
      name: apimanagers.apps.3scale.net.3scale.net
      version: v1alpha1
  description: TO BE UPDATED
  displayName: 3scale Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - 3scale
  links:
  - name: 3scale Operator
    url: https://3scale-operator.domain
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.0
