kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 3scale-operator
subjects:
  - kind: ServiceAccount
    name: 3scale-operator
    namespace: <placeholder>
roleRef:
  kind: ClusterRole
  name: 3scale-operator
  apiGroup: rbac.authorization.k8s.io
