apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: 3scale-operator
rules:
  - apiGroups:
      - console.openshift.io
    resources:
      - consolelinks
    verbs:
      - create
      - delete
      - get
      - update
