apiVersion: apps/v1
kind: Deployment
metadata:
  name: 3scale-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: threescale-operator
  template:
    metadata:
      labels:
        name: threescale-operator
    spec:
      serviceAccountName: 3scale-operator
      containers:
        - name: 3scale-operator
          image: REPLACE_IMAGE
          command:
            - 3scale-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "threescale-operator"
            - name: APISONATOR_IMAGE
              value: "quay.io/3scale/apisonator:nightly"
            - name: APICAST_IMAGE
              value: "quay.io/3scale/apicast:nightly"
            - name: PORTA_IMAGE
              value: "quay.io/3scale/porta:nightly"
            - name: ZYNC_IMAGE
              value: "quay.io/3scale/zync:nightly"
            - name: PORTA_MEMCACHED_IMAGE
              value: "memcached:1.5"
