apiVersion: apps/v1
kind: Deployment
metadata:
  name: 3scale-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: threescale-operator
  template:
    metadata:
      labels:
        name: threescale-operator
        com.redhat.product-name: 3scale
        com.redhat.component-name: 3scale-operator
        com.redhat.product-version: master
        com.redhat.component-version: 0.7.0
        com.redhat.component-type: infrastructure
    spec:
      serviceAccountName: 3scale-operator
      containers:
        - name: 3scale-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
            - 3scale-operator
          resources:
            requests:
              cpu: 10m
              memory: 100m
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "threescale-operator"
            - name: BACKEND_IMAGE
              value: "quay.io/3scale/apisonator:nightly"
            - name: APICAST_IMAGE
              value: "quay.io/3scale/apicast:nightly"
            - name: SYSTEM_IMAGE
              value: "quay.io/3scale/porta:nightly"
            - name: ZYNC_IMAGE
              value: "quay.io/3scale/zync:nightly"
            - name: SYSTEM_MEMCACHED_IMAGE
              value: "memcached:1.5"
            - name: BACKEND_REDIS_IMAGE
              value: "centos/redis-32-centos7"
            - name: SYSTEM_REDIS_IMAGE
              value: "centos/redis-32-centos7"
            - name: SYSTEM_MYSQL_IMAGE
              value: "centos/mysql-57-centos7"
            - name: SYSTEM_POSTGRESQL_IMAGE
              value: "centos/postgresql-10-centos7"
            - name: ZYNC_POSTGRESQL_IMAGE
              value: "centos/postgresql-10-centos7"
            - name: OC_CLI_IMAGE
              value: "quay.io/openshift/origin-cli:4.2"
