apiVersion: apps/v1
kind: Deployment
metadata:
  name: 3scale-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: threescale-operator
  template:
    metadata:
      labels:
        name: threescale-operator
    spec:
      serviceAccountName: 3scale-operator
      containers:
        - name: 3scale-operator
          image: quay.io/3scale/3scale-operator:msoriano-test
          command:
            - 3scale-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "threescale-operator"
