apiVersion: apps/v1
kind: Deployment
metadata:
  name: 3scale-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: threescale-operator
  template:
    metadata:
      labels:
        name: threescale-operator
        com.redhat.product-name: 3scale
        com.redhat.component-name: 3scale-operator
        com.redhat.product-version: "2.9"
        com.redhat.component-version: "0.6.0"
        com.redhat.component-type: infrastructure
    spec:
      serviceAccountName: 3scale-operator
      containers:
        - name: 3scale-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
            - 3scale-operator
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "threescale-operator"
            - name: BACKEND_IMAGE
              value: "quay.io/3scale/apisonator:nightly"
            - name: APICAST_IMAGE
              value: "quay.io/3scale/apicast:nightly"
            - name: SYSTEM_IMAGE
              value: "quay.io/3scale/porta:nightly"
            - name: ZYNC_IMAGE
              value: "quay.io/3scale/zync:nightly"
            - name: SYSTEM_MEMCACHED_IMAGE
              value: "registry.redhat.io/3scale-amp2/memcached-rhel7:3scale2.8"
            - name: BACKEND_REDIS_IMAGE
              value: "registry.redhat.io/rhscl/redis-32-rhel7:3.2"
            - name: SYSTEM_REDIS_IMAGE
              value: "registry.redhat.io/rhscl/redis-32-rhel7:3.2"
            - name: SYSTEM_MYSQL_IMAGE
              value: "registry.redhat.io/rhscl/mysql-57-rhel7:5.7"
            - name: SYSTEM_POSTGRESQL_IMAGE
              value: "registry.redhat.io/rhscl/postgresql-10-rhel7"
            - name: ZYNC_POSTGRESQL_IMAGE
              value: "registry.redhat.io/rhscl/postgresql-10-rhel7"
            - name: OC_CLI_IMAGE
              value: "registry.redhat.io/openshift4/ose-cli:4.2"
