apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: 3scale-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - "get"
  - "create"
- apiGroups:
  - api.3scale.net
  - amp.3scale.net
  resources:
  - '*'
  - consolidateds
  - bindings
  - metrics
  - plans
  - limits
  - mappingrules
  resources:
  - '*'
  verbs:
  - '*'
  - "get"
  - "create"
- apiGroups:
  - api.3scale.net
  resources:
  - '*'
  - consolidateds
  - bindings
  - metrics
  - plans
  - limits
  - mappingrules
  - amp.3scale.net
  verbs:
  - '*'
