- job_name: openshift-monitoring-federation
  honor_labels: true
  static_configs:
    - targets:
      - 'prometheus-k8s.openshift-monitoring.svc:9091'
  scrape_interval: 30s
  metrics_path: /federate
  params:
    match[]:
    - '{endpoint="https-metrics"}'
    - '{service="kube-state-metrics"}'
    - '{service="node-exporter"}'
    - '{__name__=~"namespace_pod_name_container_name:.*"}'
    - '{__name__=~"node_namespace_pod_container:.*"}'
    - '{__name__=~"node:.*"}'
    - '{__name__=~"instance:.*"}'
    - '{__name__=~"container_memory_.*"}'
    - '{__name__=~":node_memory_.*"}'
  scheme: https
  tls_config:
    insecure_skip_verify: true
  basic_auth:
    username: "internal"
    password: "<BASIC_AUTH_PASSWD>"
  metric_relabel_configs:
  - action: labeldrop
    regex: prometheus_replica
