apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: example-grafana
spec:
  config:
    log:
      mode: "console"
      level: "debug"
    security:
      admin_password: "1234"
      admin_user: "admin"
    auth:
      disable_login_form: False
      disable_signout_menu: True
    auth.basic:
      enabled: true
    auth.anonymous:
      enabled: True
  dashboardLabelSelector:
  - matchExpressions:
    - key: monitoring-key
      operator: In
      values:
      - middleware
  ingress:
    enabled: true
