# The following patch adds `oneOf` OpenAPI
# validation for the activeDocOpenAPIRef attribute
# to the ActiveDoc CRD due to at the moment
# of writing this (2020-11-02) kubebuilder
# does not support `oneOf` statement
# OpenAPI validation
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/activeDocOpenAPIRef/oneOf
  value:
    - required: ["secretRef"]
    - required: ["url"]
