# The following patch adds `oneOf` OpenAPI
# validation for the authentication attribute
# to the Product CRD due to at the moment
# of writing this (2020-11-02) kubebuilder
# does not support `oneOf` statement
# OpenAPI validation
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/deployment/properties/apicastHosted/properties/authentication/oneOf
  value:
    - required: ["userkey"]
    - required: ["appKeyAppID"]
    - required: ["oidc"]
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/deployment/properties/apicastSelfManaged/properties/authentication/oneOf
  value:
    - required: ["userkey"]
    - required: ["appKeyAppID"]
    - required: ["oidc"]
