# The following patch adds `oneOf` OpenAPI
# validation for the authentication attribute
# to the Product CRD due to at the moment
# of writing this (2020-11-02) kubebuilder
# does not support `oneOf` statement
# OpenAPI validation
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: products.capabilities.3scale.net
spec:
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            deployment:
              properties:
                apicastHosted:
                  properties:
                    authentication:
                      oneOf:
                      - required: ["userkey"]
                      - required: ["appKeyAppID"]
                      - required: ["oidc"]
                apicastSelfManaged:
                  properties:
                    authentication:
                      oneOf:
                      - required: ["userkey"]
                      - required: ["appKeyAppID"]
                      - required: ["oidc"]
