apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: apimanager-dev-latest-sample
spec:
  wildcardDomain: example.com
  apicast:
    image: "quay.io/3scale/apicast:latest"
  backend:
    image: "quay.io/3scale/apisonator:latest"
  system:
    image: "quay.io/3scale/porta:latest"
  zync:
    image: "quay.io/3scale/zync:latest"
