apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: apimanager-apicast-custom-environment
spec:
  wildcardDomain: <desired-domain>
  apicast:
    productionSpec:
      customPolicies:
        - name: Example
          version: "0.1"
          secretRef:
            name: cp-1
    stagingSpec:
      customPolicies:
        - name: Example
          version: "0.1"
          secretRef:
            name: cp-1
