apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    app: 3scale-api-management
    prometheus: application-monitoring
    role: alert-rules
    threescale_component: backend
  name: backend-worker
spec:
  groups:
  - name: __NAMESPACE__/backend-worker.rules
    rules:
    - alert: ThreescaleBackendWorkerJobsCountRunningHigh
      annotations:
        description: '{{$labels.container_name}} replica controller on {{$labels.namespace}}
          project: Has more than 1000 jobs processed in the last 5 minutes'
        summary: '{{$labels.container_name}} replica controller on {{$labels.namespace}}:
          Has more than 10000 jobs processed in the last 5 minutes'
      expr: sum(avg_over_time(apisonator_worker_job_count{job=~"backend.*",namespace="__NAMESPACE__"}
        [5m])) by (namespace,job) > 10000
      for: 5m
      labels:
        severity: critical
    - alert: ThreescaleBackendWorkerJobDown
      annotations:
        description: Job {{ $labels.job }} on {{ $labels.namespace }} is DOWN
        summary: Job {{ $labels.job }} on {{ $labels.namespace }} is DOWN
      expr: up{job=~".*backend-worker.*",namespace="__NAMESPACE__"} == 0
      for: 1m
      labels:
        severity: critical
