apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    app: 3scale-api-management
    prometheus: application-monitoring
    role: alert-rules
    threescale_component: system
  name: system-app
spec:
  groups:
  - name: __NAMESPACE__/system-app.rules
    rules:
    - alert: ThreescaleSystemApp5XXRequestsHigh
      annotations:
        description: Job {{ $labels.job }} on {{ $labels.namespace }} has more than 50 HTTP 5xx requests in the last minute
        sop_url: https://github.com/3scale/3scale-Operations/blob/master/sops/alerts/system_app_5xx_requests_high.adoc
        summary: Job {{ $labels.job }} on {{ $labels.namespace }} has more than 50 HTTP 5xx requests in the last minute
      expr: sum(rate(rails_requests_total{namespace="__NAMESPACE__",pod=~"system-app-[a-z0-9]+-[a-z0-9]+",status=~"5[0-9]*"}[1m])) by (namespace,job) > 50
      for: 1m
      labels:
        severity: warning
    - alert: ThreescaleSystemAppJobDown
      annotations:
        description: Job {{ $labels.job }} on {{ $labels.namespace }} is DOWN
        sop_url: https://github.com/3scale/3scale-Operations/blob/master/sops/alerts/prometheus_job_down.adoc
        summary: Job {{ $labels.job }} on {{ $labels.namespace }} is DOWN
      expr: up{job=~".*system-app.*",namespace="__NAMESPACE__"} == 0
      for: 1m
      labels:
        severity: critical
