apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    app: 3scale-api-management
    prometheus: application-monitoring
    role: alert-rules
    threescale_component: system
  name: system-sidekiq
spec:
  groups:
  - name: __NAMESPACE__/system-sidekiq.rules
    rules:
    - alert: ThreescaleSystemSidekiqJobDown
      annotations:
        description: Job {{ $labels.job }} on {{ $labels.namespace }} is DOWN
        summary: Job {{ $labels.job }} on {{ $labels.namespace }} is DOWN
      expr: up{job=~".*system-sidekiq.*",namespace="__NAMESPACE__"} == 0
      for: 1m
      labels:
        severity: critical
