apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: operator-requirements
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: 3scale-api-management-operator-requirements
    data:
      rht_threescale_version_requirements: ${THREESCALE_VERSION}
      rht_mysql_requirements: 8.0.0
      rht_postgres_requirements: 15.0.0
      rht_system_redis_requirements: 7.0.0
      rht_backend_redis_requirements: 7.0.0
parameters:
  - name: THREESCALE_VERSION