apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: system-database
                  key: DB_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: system-database
                  key: DB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: system-database
                  key: DB_PASSWORD
            - name: MYSQL_DATABASE
              value: dev
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql/data
            - name: mysql-main-conf-volume
              mountPath: /etc/mysql/conf.d
              readOnly: true
            - name: mysql-extra-conf-volume
              mountPath: /etc/mysql-extra.d
              readOnly: true
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: system-mysql-pvc
        - name: mysql-main-conf-volume
          configMap:
            name: mysql-main-conf
        - name: mysql-extra-conf-volume
          configMap:
            name: mysql-extra-conf
