apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-extra-conf
  labels:
    app: mysql
data:
  mysql-charset.cnf: |
    [client]
    default-character-set = utf8

    [mysql]
    default-character-set = utf8

    [mysqld]
    character-set-server = utf8
    collation-server = utf8_unicode_ci
  mysql-default-authentication-plugin.cnf: |
    [mysqld]
    default_authentication_plugin = mysql_native_password
