apiVersion: v1
kind: Secret
metadata:
  name: system-database
stringData:
  DB_USER: mysql
  DB_PASSWORD: password
  DB_ROOT_PASSWORD: rootpassword
  URL: mysql2://root:rootpassword@system-mysql.$(NAMESPACE).svc.cluster.local/dev
type: Opaque