name: Build images for master branch

on:
  push:
    branches: ['master']

jobs:
  workflow-build:
    name: Calls build-images-base workflow
    uses: ./.github/workflows/build-images-base.yml
    secrets: inherit
